
@Restaurant.API_HostAddress = http://localhost:5104/api

POST {{Restaurant.API_HostAddress}}/Restaurants
Content-Type: application/json

{
  "name": "Hambola",
  "category": "Indian",
  "description": "Hambola el2ola restaurant",
  "contactEmail": "Restaurant@Hambola.com",
  "city": "Cairo",
  "street":  "Hanbolooo",
  "postalCode": "19-990"
}

###

GET {{Restaurant.API_HostAddress}}/Restaurants
Accept: application/json

###

GET {{Restaurant.API_HostAddress}}/Restaurants/4
Accept: application/json

###

PATCH {{Restaurant.API_HostAddress}}/Restaurants/4
Content-Type: application/json

{
  "name": "Abo Younis",
  "description": "Agmad mt3m fkosom el3alam",
  "hasDelivery": true
}

###

DELETE {{Restaurant.API_HostAddress}}/Restaurants/4
Accept: application/json

###